CREATE TABLE `commercial_clients` (
	`id` int AUTO_INCREMENT NOT NULL,
	`external_id` int,
	`company` varchar(500) NOT NULL,
	`address` text,
	`locality` varchar(255),
	`postal_code` varchar(50),
	`county` varchar(255),
	`district` varchar(255),
	`country` varchar(100) DEFAULT 'Portugal',
	`nif` varchar(20),
	`phone1` varchar(50),
	`phone2` varchar(50),
	`fax` varchar(50),
	`mobile1` varchar(50),
	`mobile2` varchar(50),
	`email` varchar(320),
	`website` varchar(500),
	`salesperson` varchar(255),
	`zone` varchar(255),
	`payment_terms` varchar(100),
	`discount` decimal(5,2) DEFAULT '0',
	`balance` decimal(12,2),
	`active` int NOT NULL DEFAULT 1,
	`blocked` int NOT NULL DEFAULT 0,
	`client_since` date,
	`comments` text,
	`imported_at` timestamp NOT NULL DEFAULT (now()),
	`updated_at` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `commercial_clients_id` PRIMARY KEY(`id`)
);
